name: Git Commit
description: A Buildkite plugin to commit and push the results of a command to a git repository.
author: https://github.com/reidab
requirements: []
configuration:
  properties:
    add:
      type: string
    branch:
      type: string
    create-branch:
      type: boolean
    message:
      type: string
    tag:
      type: string
    tag-message:
      type: string
    remote:
      type: string
    pull-request:
      type: boolean
    pull-request-labels:
      type: string
    pull-request-message:
      type: string
    pull-request-base-branch:
      type: string
    pull-request-wait-for-merge:
      type: boolean
    pull-request-wait-for-merge-timeout-mins:
      type: string
    user:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
